# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0014_remove_profile_hometown'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='documents/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilePic', to='User_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
