# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0015_auto_20170904_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='hometown',
        ),
    ]
