# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0016_auto_20170905_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='fav_movie',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hometown',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
