# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('api_code', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=10)),
                ('episode', models.CharField(max_length=10)),
                ('series_title', models.CharField(max_length=50)),
                ('episode_title', models.CharField(max_length=50)),
                ('still_path', models.CharField(max_length=100)),
                ('poster_path', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=140)),
                ('score', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_rating', models.PositiveSmallIntegerField(null=True)),
                ('entertainment_rating', models.PositiveSmallIntegerField(null=True)),
                ('acting_rating', models.PositiveSmallIntegerField(null=True)),
                ('visual_rating', models.PositiveSmallIntegerField(null=True)),
                ('sound_rating', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('api_code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('poster_path', models.CharField(max_length=100)),
                ('backdrop_path', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=140)),
                ('score', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_rating', models.PositiveSmallIntegerField(null=True)),
                ('entertainment_rating', models.PositiveSmallIntegerField(null=True)),
                ('acting_rating', models.PositiveSmallIntegerField(null=True)),
                ('visual_rating', models.PositiveSmallIntegerField(null=True)),
                ('sound_rating', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('api_code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('poster_path', models.CharField(max_length=100)),
                ('backdrop_path', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=140)),
                ('score', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_rating', models.PositiveSmallIntegerField(null=True)),
                ('entertainment_rating', models.PositiveSmallIntegerField(null=True)),
                ('acting_rating', models.PositiveSmallIntegerField(null=True)),
                ('visual_rating', models.PositiveSmallIntegerField(null=True)),
                ('sound_rating', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_review', models.ManyToManyField(related_name='episodes', to='movieApp.EpisodeReview')),
                ('movie_review', models.ManyToManyField(related_name='movies', to='movieApp.MovieReview')),
                ('tv_review', models.ManyToManyField(related_name='tvs', to='movieApp.TVReview')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='User_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_code', models.CharField(max_length=100)),
                ('movie_title', models.CharField(max_length=50)),
                ('poster_path', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_app.User')),
            ],
        ),
    ]
