# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0009_auto_20170904_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='api_Movie_code',
            new_name='api_code',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
