# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0010_auto_20170904_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodereview',
            name='acting_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='episodereview',
            name='entertainment_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='episodereview',
            name='sound_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='episodereview',
            name='story_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='episodereview',
            name='visual_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='entertainment_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='sound_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='story_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='visual_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tvreview',
            name='acting_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tvreview',
            name='entertainment_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tvreview',
            name='sound_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tvreview',
            name='story_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tvreview',
            name='visual_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
