# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0011_auto_20170914_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='acting_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
