# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0012_moviereview_acting_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='_type',
            new_name='media_type',
        ),
    ]
